### ISSUE TITLE
Don't silently proceed on parse failure

### ISSUE THREAD

**Issue by feifanzhou** [tendant/graphql-clj#17]
![screen shot 2016-10-09 at 17 18 11](https://cloud.githubusercontent.com/assets/3407996/19224920/6e503d08-8e44-11e6-901b-4e7d602813b9.png)

It's possible to create a schema despite a parse failure, which leads to more subtle failures ("Field does not exist on Type", etc) when trying to actually use the schema. Instead, the parse failure should throw an exception at some point (preferably the `parser/parse` or `type/create-schema` call).

(Incidentally, in this case the parse failure is because the open quote is immediately followed by a newline. Moving the open quote to the first line of the schema string fixes this failure)

**Comment by tendant** [comment]
Added assert in type/create-schema to check if parsed schema is an insta/failure.

parser/parse still just return instaparse.gll.Failure, since executor needs the failure information to construct executing result.

**Comment by tendant** [comment]
Details: https://github.com/tendant/graphql-clj/commit/782a57797b4a6b925b17d0ab0a333dfded8151e6
