### ISSUE TITLE
Can't seem to use aliases

### ISSUE THREAD

**Issue by dadair-ca** [tendant/graphql-clj#19]
Hi! I'll preface this with that I'm relatively new to graphql, so this could be just a noob mistake!

I'm putting together a simple project to play around with graphql-clj (and graphql in general), but I can't seem to alias my queries. I've looked at your tests and I know aliasing should work, but I can't seem to make it happen.

I've included a screenshot of the entirety of my codebase (super small!). Would you perhaps be able to point out an incorrect use of the library (or perhaps a mistake in the query/schema) that is preventing my attempts at aliasing? I want to make sure this is a mistake on my end, and not some bug.

If I reorder the aliased lines in the query, I always receive only the last-requested user, and the returned data is not aliased.

Thanks for your help! And thanks for the lib!

![2016-10-11-154028_1361x1078_scrot](https://cloud.githubusercontent.com/assets/594099/19289783/9ffd936a-8fc9-11e6-99b4-a2f5bd4f55c7.png)

**Comment by tendant** [comment]
Thanks to @sickill, this issue has been fixed today. Just release a new version 0.1.15 for the fix. Please try the new version.

Thanks for reporting the issue.
